// Code generated by `mygo generate`. DO NOT EDIT.

import { call, event } from "mygo-runtime";

// ---- Types ----

/** App is an application of a server, which sends messages. */
export interface App {
  id: number;
  name: string;
  description: string;
  /** ImageKey changes with the app's image; empty when it has none. AppImage returns it. */
  imageKey: string;
  unread: number;
  muted: boolean;
  minPriority: number | null;
}

/** AppPrefs are the notification preferences of an app. */
export interface AppPrefs {
  muted: boolean;
  /** MinPriority hides notifications of lower priority; null shows all. */
  minPriority: number | null;
}

/** CAFile is a CA certificate the user chose. */
export interface CAFile {
  name: string;
  pem: string;
}

/** ConnState is the state of a server's connection. */
export type ConnState = "connected" | "connecting" | "backoff" | "authFailed" | "disconnected";

/** Language is a language the app can show, or "" for the system's. */
export type Language = "" | "en" | "zh-CN";

/** Message is a received message. */
export interface Message {
  serverId: number;
  id: number;
  appId: number;
  title: string;
  body: string;
  markdown: boolean;
  priority: number;
  date: string;
  read: boolean;
  /** ClickURL is where clicking the message's notification leads. */
  clickUrl: string;
}

/** MessagePage is a page of messages. */
export interface MessagePage {
  messages: Message[];
  /** HasMore is true when a larger limit would return more messages. */
  hasMore: boolean;
  /** MsgGen is the State.MsgGen the page was read at. */
  msgGen: number;
}

/** MessageRef identifies a message. */
export interface MessageRef {
  serverId: number;
  id: number;
}

/** Navigation names a server, an app and a message to show; zero values widen it. */
export interface Navigation {
  serverId: number;
  appId: number;
  messageId: number;
}

/** Query selects messages, newest first. */
export interface Query {
  /** ServerID and AppID narrow the messages to a server and one of its apps; 0 is all. */
  serverId: number;
  appId: number;
  search: string;
  limit: number;
  /** Include grows the page until it holds this message, if it is in the scope. */
  include: MessageRef | null;
}

/** Server is a Gotify server and its connection. */
export interface Server {
  id: number;
  name: string;
  url: string;
  insecure: boolean;
  hasCA: boolean;
  state: ConnState;
  /** Error explains why the server is not connected. */
  error: string;
  /** RetryAt is when a server in backoff tries again. */
  retryAt: string | null;
  apps: App[];
  unread: number;
}

/** ServerForm adds a server, edits it or signs in to it again. */
export interface ServerForm {
  name: string;
  url: string;
  user: string;
  pass: string;
  insecure: boolean;
  /** CA is a PEM CA certificate to trust; empty for none. */
  ca: string;
  /** KeepCA makes UpdateServer leave the server's CA certificate as it is. */
  keepCA: boolean;
}

/** Settings are the notification settings the user edits. */
export interface Settings {
  /** PausedUntil is when paused notifications resume; null when they are not paused. */
  pausedUntil: string | null;
  dnd: boolean;
  /** DNDStart and DNDEnd are minutes of the day; the window may wrap midnight. */
  dndStart: number;
  dndEnd: number;
  highBypassesDnd: boolean;
  /** Language is the language the user chose; "" follows the system. */
  language: Language;
  /** Theme is the appearance the user chose; "" follows the system. */
  theme: Theme;
}

/** State is everything the page shows besides messages. */
export interface State {
  servers: Server[];
  unread: number;
  settings: Settings;
  /** Gen grows with every change: a state with a lower one is out of date. */
  gen: number;
  /** MsgGen changes whenever messages were added, read or deleted. */
  msgGen: number;
  /** SettingsSeq is the sequence number of the newest settings write; see SettingsEpoch. */
  settingsSeq: number;
  /** Language is the language to show: Settings.Language, or the system's. */
  lang: Language;
  version: string;
  dataDir: string;
  openAtLogin: boolean;
}

/** Theme is a light or dark appearance, or "" for the system's. */
export type Theme = "" | "light" | "dark";

// ---- Services ----

/** Desktop is the service the page calls. */
export const Desktop = {
  /** AddServer signs in to a server and adds it. It returns the new server's ID. */
  addServer(f: ServerForm): Promise<number> {
    return call("Desktop.AddServer", f);
  },
  /** AppImage returns the image of an app as a data URL, or "" when it has none. */
  appImage(serverID: number, appID: number): Promise<string> {
    return call("Desktop.AppImage", serverID, appID);
  },
  /** CopyText puts text on the clipboard. */
  copyText(text: string): Promise<void> {
    return call("Desktop.CopyText", text);
  },
  /** DeleteMessage deletes a message on its server and here. */
  deleteMessage(serverID: number, id: number): Promise<void> {
    return call("Desktop.DeleteMessage", serverID, id);
  },
  /** MarkAllRead marks the messages of an app, a server (appID 0) or every server (serverID 0) read. */
  markAllRead(serverID: number, appID: number): Promise<void> {
    return call("Desktop.MarkAllRead", serverID, appID);
  },
  /** MarkRead marks messages of a server read. */
  markRead(serverID: number, ids: number[]): Promise<void> {
    return call("Desktop.MarkRead", serverID, ids);
  },
  /** Messages returns the newest messages that match q. */
  messages(q: Query): Promise<MessagePage> {
    return call("Desktop.Messages", q);
  },
  /** OpenURL opens an http(s) or mailto URL in the default app. */
  openURL(raw: string): Promise<void> {
    return call("Desktop.OpenURL", raw);
  },
  /** PickCA asks for a CA certificate file. It returns null when the user canceled. */
  pickCA(): Promise<CAFile | null> {
    return call("Desktop.PickCA");
  },
  /** Relogin signs in to a server again after its session ended. */
  relogin(serverID: number, user: string, pass: string): Promise<void> {
    return call("Desktop.Relogin", serverID, user, pass);
  },
  /** RemoveServer signs out of a server and deletes its messages from this computer. */
  removeServer(serverID: number): Promise<void> {
    return call("Desktop.RemoveServer", serverID);
  },
  /** SetAppPrefs saves the notification preferences of an app. */
  setAppPrefs(serverID: number, appID: number, p: AppPrefs): Promise<void> {
    return call("Desktop.SetAppPrefs", serverID, appID, p);
  },
  /** SetOpenAtLogin starts the app at login, or stops doing so. */
  setOpenAtLogin(on: boolean): Promise<void> {
    return call("Desktop.SetOpenAtLogin", on);
  },
  /**
   * SetSettings saves the notification settings.
   *
   * seq orders the writes, which may arrive in any order: a write numbered no
   * higher than one already saved is dropped. Pages number their writes on from
   * SettingsEpoch.
   */
  setSettings(seq: number, s: Settings): Promise<void> {
    return call("Desktop.SetSettings", seq, s);
  },
  /**
   * SettingsEpoch returns a number for a page to number its settings writes
   * from: epoch<<20 plus a count of its writes. Every call returns a higher one
   * than before, above every write saved, so a page loaded later wins over one
   * loaded earlier, even while the earlier page's writes are still on their way.
   */
  settingsEpoch(): Promise<number> {
    return call("Desktop.SettingsEpoch");
  },
  /** State returns the servers, their apps, the unread counts and the settings. */
  state(): Promise<State> {
    return call("Desktop.State");
  },
  /** TakeNavigation returns the navigation a clicked notification asked for, once, or null. */
  takeNavigation(): Promise<Navigation | null> {
    return call("Desktop.TakeNavigation");
  },
  /** TestNotification shows a sample notification. */
  testNotification(): Promise<void> {
    return call("Desktop.TestNotification");
  },
  /** UpdateServer changes a server's name and TLS options. */
  updateServer(serverID: number, f: ServerForm): Promise<void> {
    return call("Desktop.UpdateServer", serverID, f);
  },
} as const;

// ---- Events ----

/** Events sent by the Go side. Subscribe with `events.name.on(listener)`. */
export const events = {
  /** StateChanged carries the new state after every change. */
  state: event<State>("state"),
  /** NavigateRequested asks the page to show a message, after a notification was clicked. */
  navigate: event<Navigation>("navigate"),
} as const;
